package com.rhwayfun.springboot.security.datasource.model;

public class UserAuthority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_auth_user.id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_auth_user.user_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_auth_user.auth_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    private Integer authId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_auth_user.id
     *
     * @return the value of r_auth_user.id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_auth_user.id
     *
     * @param id the value for r_auth_user.id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_auth_user.user_id
     *
     * @return the value of r_auth_user.user_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_auth_user.user_id
     *
     * @param userId the value for r_auth_user.user_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_auth_user.auth_id
     *
     * @return the value of r_auth_user.auth_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public Integer getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_auth_user.auth_id
     *
     * @param authId the value for r_auth_user.auth_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }
}