package com.rhwayfun.springboot.security.datasource.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_users.id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_users.user_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_users.user_name
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    private String userName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_users.id
     *
     * @return the value of g_users.id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_users.id
     *
     * @param id the value for g_users.id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_users.user_id
     *
     * @return the value of g_users.user_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_users.user_id
     *
     * @param userId the value for g_users.user_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_users.user_name
     *
     * @return the value of g_users.user_name
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_users.user_name
     *
     * @param userName the value for g_users.user_name
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }
}