package com.rhwayfun.springboot.security.datasource.mapper;

import com.rhwayfun.springboot.security.datasource.model.Authority;
import com.rhwayfun.springboot.security.datasource.model.AuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_authority
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    long countByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_authority
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int deleteByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_authority
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_authority
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int insert(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_authority
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int insertSelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_authority
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    List<Authority> selectByExample(AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_authority
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    Authority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_authority
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") Authority record, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_authority
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByExample(@Param("record") Authority record, @Param("example") AuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_authority
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByPrimaryKeySelective(Authority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_authority
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByPrimaryKey(Authority record);
}