package com.rhwayfun.springboot.security.datasource.mapper;

import com.rhwayfun.springboot.security.datasource.model.UserAuthority;
import com.rhwayfun.springboot.security.datasource.model.UserAuthorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_user
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    long countByExample(UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_user
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int deleteByExample(UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_user
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_user
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int insert(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_user
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int insertSelective(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_user
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    List<UserAuthority> selectByExample(UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_user
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    UserAuthority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_user
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") UserAuthority record, @Param("example") UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_user
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByExample(@Param("record") UserAuthority record, @Param("example") UserAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_user
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByPrimaryKeySelective(UserAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_auth_user
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByPrimaryKey(UserAuthority record);
}