package com.rhwayfun.springboot.quickstart.security.datasource.mapper;

import com.rhwayfun.springboot.quickstart.security.datasource.model.User;
import com.rhwayfun.springboot.quickstart.security.datasource.model.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_users
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_users
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_users
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_users
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_users
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_users
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_users
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_users
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_users
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_users
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_users
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    int updateByPrimaryKey(User record);
}