package com.rhwayfun.springboot.quickstart.security.datasource.model;

public class Authority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_authority.id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_authority.auth_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    private Integer authId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_authority.auth_name
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    private String authName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_authority.id
     *
     * @return the value of g_authority.id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_authority.id
     *
     * @param id the value for g_authority.id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_authority.auth_id
     *
     * @return the value of g_authority.auth_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public Integer getAuthId() {
        return authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_authority.auth_id
     *
     * @param authId the value for g_authority.auth_id
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public void setAuthId(Integer authId) {
        this.authId = authId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_authority.auth_name
     *
     * @return the value of g_authority.auth_name
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public String getAuthName() {
        return authName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_authority.auth_name
     *
     * @param authName the value for g_authority.auth_name
     *
     * @mbg.generated Sun Aug 13 20:54:51 CST 2017
     */
    public void setAuthName(String authName) {
        this.authName = authName == null ? null : authName.trim();
    }
}